<?php

/**
 * @file
 * Primary module hooks for Content Moderation Link module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function content_moderation_link_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the content_moderation_links module.
    case 'help.page.content_moderation_links':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module allows editors to move content to a different workflow state by
accessing a specially crafted URL') . '</p>';
      return $output;
  }
}
